version: "3.8"

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP monitoring port
    environment:
      - NATS_LOG_LEVEL=debug
      - NATS_MAX_PAYLOAD=1048576

  social-stream-grpc-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - IS_DEVELOPMENT=true
      - DEBUG=true
      - NATS_URL=nats://nats-server:4222
      - GRPC_PORT=0.0.0.0:50051