// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: social-stream.proto

package social_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublisherResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PublisherResponce) Reset() {
	*x = PublisherResponce{}
	mi := &file_social_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherResponce) ProtoMessage() {}

func (x *PublisherResponce) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherResponce.ProtoReflect.Descriptor instead.
func (*PublisherResponce) Descriptor() ([]byte, []int) {
	return file_social_stream_proto_rawDescGZIP(), []int{0}
}

func (x *PublisherResponce) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublisherResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublisherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PublisherRequest) Reset() {
	*x = PublisherRequest{}
	mi := &file_social_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherRequest) ProtoMessage() {}

func (x *PublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherRequest.ProtoReflect.Descriptor instead.
func (*PublisherRequest) Descriptor() ([]byte, []int) {
	return file_social_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PublisherRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PublisherRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SubcribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subjects []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
}

func (x *SubcribeRequest) Reset() {
	*x = SubcribeRequest{}
	mi := &file_social_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubcribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubcribeRequest) ProtoMessage() {}

func (x *SubcribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubcribeRequest.ProtoReflect.Descriptor instead.
func (*SubcribeRequest) Descriptor() ([]byte, []int) {
	return file_social_stream_proto_rawDescGZIP(), []int{2}
}

func (x *SubcribeRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type SubcribeResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg     string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *SubcribeResponce) Reset() {
	*x = SubcribeResponce{}
	mi := &file_social_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubcribeResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubcribeResponce) ProtoMessage() {}

func (x *SubcribeResponce) ProtoReflect() protoreflect.Message {
	mi := &file_social_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubcribeResponce.ProtoReflect.Descriptor instead.
func (*SubcribeResponce) Descriptor() ([]byte, []int) {
	return file_social_stream_proto_rawDescGZIP(), []int{3}
}

func (x *SubcribeResponce) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SubcribeResponce) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_social_stream_proto protoreflect.FileDescriptor

var file_social_stream_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e,
	0x0a, 0x10, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2d,
	0x0a, 0x0f, 0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x3e, 0x0a,
	0x10, 0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x85, 0x01,
	0x0a, 0x12, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0e,
	0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x10,
	0x2e, 0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x65, 0x6c, 0x39, 0x64, 0x6f, 0x74, 0x2f, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_social_stream_proto_rawDescOnce sync.Once
	file_social_stream_proto_rawDescData = file_social_stream_proto_rawDesc
)

func file_social_stream_proto_rawDescGZIP() []byte {
	file_social_stream_proto_rawDescOnce.Do(func() {
		file_social_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_social_stream_proto_rawDescData)
	})
	return file_social_stream_proto_rawDescData
}

var file_social_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_social_stream_proto_goTypes = []any{
	(*PublisherResponce)(nil), // 0: PublisherResponce
	(*PublisherRequest)(nil),  // 1: PublisherRequest
	(*SubcribeRequest)(nil),   // 2: SubcribeRequest
	(*SubcribeResponce)(nil),  // 3: SubcribeResponce
}
var file_social_stream_proto_depIdxs = []int32{
	1, // 0: SocialSteamService.PublishTrades:input_type -> PublisherRequest
	2, // 1: SocialSteamService.SubcribeTrades:input_type -> SubcribeRequest
	0, // 2: SocialSteamService.PublishTrades:output_type -> PublisherResponce
	3, // 3: SocialSteamService.SubcribeTrades:output_type -> SubcribeResponce
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_stream_proto_init() }
func file_social_stream_proto_init() {
	if File_social_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_social_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_stream_proto_goTypes,
		DependencyIndexes: file_social_stream_proto_depIdxs,
		MessageInfos:      file_social_stream_proto_msgTypes,
	}.Build()
	File_social_stream_proto = out.File
	file_social_stream_proto_rawDesc = nil
	file_social_stream_proto_goTypes = nil
	file_social_stream_proto_depIdxs = nil
}
